# Generated by Django 3.0.7 on 2020-06-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titlee',
            new_name='title',
        ),
    ]
